# ==========================
# APPLICATION
# ==========================
spring.application.name=notification-service
server.port=5009

# ==========================
# DATABASE
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/notification
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================
# EUREKA
# ==========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# ==========================
# FEIGN
# ==========================
spring.cloud.openfeign.httpclient.hc5.enabled=true

# ==========================
# KAFKA
# ==========================
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

# Error Handling Deserializer
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Delegate Deserializers
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Ignore producer's type headers
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# Deserialize into Notification Service DTO
spring.kafka.consumer.properties.spring.json.value.default.type=com.hca.notification_service.dto.AppointmentReservedEvent

# Trusted Packages
spring.kafka.consumer.properties.spring.json.trusted.packages=com.hca.notification_service.dto

# ==========================
# LOGGING
# ==========================
logging.level.root=INFO
logging.level.org.springframework.kafka=INFO
logging.level.org.apache.kafka=INFO