services:
  api-gateway:
    image: healthcare/api-gateway:1.0
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "5000:5000"
#    depends_on:
#      eureka-server:
#        condition: service_started
    environment:
      #EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
      JWT_SECRET: b7f3a9c2d1e4f6a8b9c0d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3
    restart: unless-stopped
    networks: [ healthcare-network ]

networks:
  healthcare-network:
    external: true
