mysql:
  image: mysql:8.4

  container_name: mysql

  ports:
    - "3306:3306"

  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: healthcare

  volumes:

    - mysql-data:/var/lib/mysql

    - ./docker/mysql/init:/docker-entrypoint-initdb.d

  networks:
    - healthcare-network