server:
  port: 5000

jwt:
  secret: b7f3a9c2...

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:63342"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: patient-service
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/api/patients/**
          filters:
            - JwtAuthenticationFilter

        - id: doctor-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/api/doctors/**
          filters:
            - JwtAuthenticationFilter

        - id: slot-service
          uri: lb://SLOT-SERVICE
          predicates:
            - Path=/api/slots/**
          filters:
            - JwtAuthenticationFilter

        - id: appointment-service
          uri: lb://APPOINTMENT-SERVICE
          predicates:
            - Path=/api/appointments/**
          filters:
            - JwtAuthenticationFilter

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
          filters:
            - JwtAuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE