version: "3.9"

services:

  ####################################################
  # MYSQL
  ####################################################

  mysql:
    image: mysql:8.4
    container_name: mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - healthcare-network

  ####################################################
  # MONGODB
  ####################################################



  eureka-server:

    image: healthcare/eureka-server:1.0

    container_name: eureka-server

    restart: unless-stopped

    ports:
      - "8761:8761"

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - healthcare-network

######################################################
# NETWORK
######################################################

networks:

  healthcare-network:

######################################################
# VOLUMES
######################################################

volumes:

  mysql-data:

  mongo-data:

  kafka-data:

api-gateway:

  build:
    context: ../api-gateway

  image: healthcare/api-gateway:1.0

  container_name: api-gateway

  ports:
    - "5000:5000"

  depends_on:

    eureka-server:
      condition: service_started

  environment:

    EUREKA_SERVER_URL: http://eureka-server:8761/eureka

    JWT_SECRET: b7f3a9c2d1e4f6a8b9c0d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3

  restart: unless-stopped

  networks:
    - healthcare-network


################
auth-service:

  build:
    context: ../auth-service

  image: healthcare/auth-service:1.0

  container_name: auth-service

  ports:
    - "5006:5006"

  depends_on:

    mysql:
      condition: service_healthy

    eureka-server:
      condition: service_started

  environment:

    MYSQL_URL: jdbc:mysql://mysql:3306/auth_db

    MYSQL_USERNAME: root

    MYSQL_PASSWORD: root

    EUREKA_SERVER_URL: http://eureka-server:8761/eureka

    JWT_SECRET: b7f3a9c2d1e4f6a8b9c0d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3

  restart: unless-stopped

  networks:
    - healthcare-network


################
patient-service:

  build:
    context: ../patient-service

  image: healthcare/patient-service:1.0

  container_name: patient-service

  ports:
    - "5003:5003"

  depends_on:

    mysql:
      condition: service_healthy

    eureka-server:
      condition: service_started

  environment:

    MYSQL_URL: jdbc:mysql://mysql:3306/patient_db

    MYSQL_USERNAME: root

    MYSQL_PASSWORD: root

    EUREKA_SERVER_URL: http://eureka-server:8761/eureka

  restart: unless-stopped

  networks:
    - healthcare-network


###############

doctor-service:

  build:
    context: ../doctor-service

  image: healthcare/doctor-service:1.0

  container_name: doctor-service

  ports:
    - "5001:5001"

  depends_on:

    eureka-server:
      condition: service_started

  environment:

    MONGODB_URI: mongodb://root:root@mongodb:27017/doctor_db?authSource=admin

    EUREKA_SERVER_URL: http://eureka-server:8761/eureka

  restart: unless-stopped

  networks:
    - healthcare-network


###########

slot-service:

  build:
    context: ../slot-service

  image: healthcare/slot-service:1.0

  container_name: slot-service

  ports:
    - "5002:5002"

  depends_on:

    mysql:
      condition: service_healthy

    eureka-server:
      condition: service_started

  environment:

    MYSQL_URL: jdbc:mysql://mysql:3306/slot_db

    MYSQL_USERNAME: root

    MYSQL_PASSWORD: root

    EUREKA_SERVER_URL: http://eureka-server:8761/eureka

  restart: unless-stopped

  networks:
    - healthcare-network


appointment-service:

  build:
    context: ../appointment-service

  image: healthcare/appointment-service:1.0

  container_name: appointment-service

  ports:
    - "5007:5007"

  depends_on:

    mysql:
      condition: service_healthy

    eureka-server:
      condition: service_started

  environment:

    MYSQL_URL: jdbc:mysql://mysql:3306/appointment_db

    MYSQL_USERNAME: root

    MYSQL_PASSWORD: root

    EUREKA_SERVER_URL: http://eureka-server:8761/eureka

    KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  restart: unless-stopped

  networks:
    - healthcare-network


#############

payment-service:

  build:
    context: ../payment-service

  image: healthcare/payment-service:1.0

  container_name: payment-service

  ports:
    - "5008:5008"

  depends_on:

    mysql:
      condition: service_healthy

    eureka-server:
      condition: service_started

  environment:

    MYSQL_URL: jdbc:mysql://mysql:3306/payment_db

    MYSQL_USERNAME: root

    MYSQL_PASSWORD: root

    EUREKA_SERVER_URL: http://eureka-server:8761/eureka

    RAZORPAY_KEY: your-test-key

    RAZORPAY_SECRET: your-test-secret

  restart: unless-stopped

  networks:
    - healthcare-network




#############

notification-service:

  build:
    context: ../notification-service

  image: healthcare/notification-service:1.0

  container_name: notification-service

  ports:
    - "5009:5009"

  depends_on:

    mysql:
      condition: service_healthy

    eureka-server:
      condition: service_started

  environment:

    MYSQL_URL: jdbc:mysql://mysql:3306/notification_db

    MYSQL_USERNAME: root

    MYSQL_PASSWORD: root

    EUREKA_SERVER_URL: http://eureka-server:8761/eureka

    KAFKA_BOOTSTRAP_SERVERS: kafka:9092

    MAIL_USERNAME: your-email@gmail.com

    MAIL_PASSWORD: your-app-password

  restart: unless-stopped

  networks:
    - healthcare-network