spring.application.name=doctor-service

server.port=5001
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}

#spring.data.mongodb.uri=mongodb://root:root@localhost:27017/health?authSource=admin
mongodb.uri=${MONGODB_URI:mongodb://root:root@localhost:27017/health?authSource=admin}
logging.level.org.springframework.security=DEBUG