CREATE DATABASE IF NOT EXISTS auth_db;

CREATE DATABASE IF NOT EXISTS patient_db;

CREATE DATABASE IF NOT EXISTS slot_db;

CREATE DATABASE IF NOT EXISTS appointment_db;

CREATE DATABASE IF NOT EXISTS payment_db;

CREATE DATABASE IF NOT EXISTS notification_db;